name: MAVSDK-Swift
options:
  deploymentTarget:
    iOS: "9.0"
  bundleIdPrefix: io.mavlink.mavsdk
settings:
  VALID_ARCHS[sdk=iphonesimulator*]: x86_64
targets:
  MAVSDK-Swift:
    name: MAVSDK_Swift
    type: framework
    platform: iOS
    info:
      path: Sources/MAVSDK-Swift/Info.plist
    scheme:
      testTargets:
        - MAVSDK_SwiftTests
        - MAVSDK_SwiftIntegrationTests
    sources: [Sources/MAVSDK-Swift]
    dependencies:
      - carthage: mavsdk_server
      - carthage: BoringSSL
      - carthage: CgRPC
      - carthage: RxSwift
      - carthage: SwiftGRPC
      - carthage: SwiftProtobuf
  MAVSDK-SwiftTests:
    name: MAVSDK_SwiftTests
    type: bundle.unit-test
    platform: iOS
    sources: [Sources/MAVSDK-SwiftTests]
    dependencies:
      - target: MAVSDK_Swift
      - carthage: mavsdk_server
      - carthage: BoringSSL
      - carthage: CgRPC
      - carthage: RxBlocking
      - carthage: RxSwift
      - carthage: RxTest
      - carthage: SwiftGRPC
      - carthage: SwiftProtobuf
  MAVSDK-SwiftIntegrationTests:
    name: MAVSDK_SwiftIntegrationTests
    type: bundle.unit-test
    platform: iOS
    sources: [Sources/MAVSDK-SwiftIntegrationTests]
    dependencies:
      - target: MAVSDK_Swift
      - carthage: mavsdk_server
      - carthage: BoringSSL
      - carthage: CgRPC
      - carthage: RxBlocking
      - carthage: RxSwift
      - carthage: RxTest
      - carthage: SwiftGRPC
      - carthage: SwiftProtobuf
